// Generated by Selenium IDE
package com.architec.crediti;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class ProfileStudentAsLectorTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void ProfileStudentAsLector() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1358, 692));
        driver.findElement(By.cssSelector("li:nth-child(1) span")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).click();
        {
            WebElement element = driver.findElement(By.id("username"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("username")).sendKeys("s093027@ap.be");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("2Q=hV$pW");
        driver.findElement(By.cssSelector("button")).click();
        driver.findElement(By.cssSelector(".find-edu")).click();
        driver.findElement(By.cssSelector("li:nth-child(3) > .dropdown")).click();
        driver.findElement(By.cssSelector("li:nth-child(3) a")).click();
        driver.findElement(By.linkText("📃")).click();
        driver.findElement(By.cssSelector(".nav")).click();
        driver.findElement(By.cssSelector("li:nth-child(3) a")).click();
        driver.findElement(By.cssSelector(".tablebackground:nth-child(3) .button")).click();
    }
}
