// Generated by Selenium IDE
package com.architec.crediti;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class ProfileStudentAsLectorTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        // moet aanwezig zijn
        System.setProperty("webdriver.gecko.driver", "C:\\Users\\Vladik\\Desktop\\geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void ProfileStudentAsStudent() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1358, 692));
        driver.findElement(By.cssSelector("li:nth-child(1) > a")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("s093027@ap.be");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("2Q=hV$pW");
        driver.findElement(By.cssSelector("button")).click();
        WebElement div = driver.findElement(By.cssSelector("div[@class='dropdown']"));
        div.click();
        WebElement li = div.findElement(By.xpath("div[@class='nav-main']/div[@class='container']/div[@class='wrap-all col-xs-12']/div[@class='right']/div[@class='region-header-menu']/div[@class='nav']/div[@class='dropdown']/li:nth-child(2) a:nth-child(2)"));
        li.click();
    }
}
