package com.architec.crediti;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class SeleniumAssignmentTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\toegepaste informatica\\J2\\M4\\Project\\geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    // id= 1
    @Test
    public void loadAllAssignments() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Lopende Opdrachten")).click();
    }
    // id= 3
    @Test
    public void deleteAssignmentInList() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Opdracht Toevoegen")).click();
        driver.findElement(By.id("title")).click();
        driver.findElement(By.id("title")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("type")).click();
        {
            WebElement dropdown = driver.findElement(By.id("type"));
            dropdown.findElement(By.xpath("//option[. = 'ZAP']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(2)")).click();
        driver.findElement(By.id("task")).click();
        driver.findElement(By.id("task")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("startDate")).click();
        driver.findElement(By.id("startDate")).sendKeys("2019-06-28");
        driver.findElement(By.id("endDate")).click();
        driver.findElement(By.id("endDate")).sendKeys("2019-06-29");
        driver.findElement(By.id("amountHours")).click();
        driver.findElement(By.id("amountHours")).sendKeys("12");
        driver.findElement(By.id("maxStudents")).click();
        driver.findElement(By.id("maxStudents")).sendKeys("6");
        driver.findElement(By.cssSelector("label:nth-child(2) > #tag")).click();
        driver.findElement(By.cssSelector(".button")).click();
        driver.findElement(By.cssSelector(".button:nth-child(3)")).click();
        driver.findElement(By.linkText("📃")).click();
        driver.findElement(By.linkText("🗑️ VERWIJDEREN")).click();
    }
    // id= 4
    @Test
    public void AddAssignmentEmpty() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Opdracht Toevoegen")).click();
        driver.findElement(By.cssSelector(".button")).click();
    }
    // id= 5
    @Test
    public void addAssignmentHalfEmpty() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Opdracht Toevoegen")).click();
        driver.findElement(By.id("title")).click();
        driver.findElement(By.id("title")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("type")).click();
        {
            WebElement dropdown = driver.findElement(By.id("type"));
            dropdown.findElement(By.xpath("//option[. = 'ZAP']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(2)")).click();
        driver.findElement(By.id("startDate")).click();
        driver.findElement(By.id("startDate")).sendKeys("2019-06-28");
        driver.findElement(By.id("endDate")).click();
        driver.findElement(By.id("endDate")).sendKeys("2019-06-29");
        driver.findElement(By.id("amountHours")).click();
        driver.findElement(By.id("amountHours")).sendKeys("12");
        driver.findElement(By.cssSelector(".button")).click();
        driver.findElement(By.id("task")).sendKeys("SELENIUMtest");
        driver.findElement(By.cssSelector(".button")).click();
    }
    // id= 7
    @Test
    public void addAssignmentEndDateSmaller() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Opdracht Toevoegen")).click();
        driver.findElement(By.id("title")).click();
        driver.findElement(By.id("title")).sendKeys("test");
        driver.findElement(By.id("type")).click();
        {
            WebElement dropdown = driver.findElement(By.id("type"));
            dropdown.findElement(By.xpath("//option[. = 'ZAP']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(2)")).click();
        driver.findElement(By.id("task")).click();
        driver.findElement(By.id("task")).sendKeys("test");
        driver.findElement(By.id("startDate")).click();
        driver.findElement(By.id("startDate")).sendKeys("2019-06-28");
        driver.findElement(By.id("endDate")).click();
        driver.findElement(By.id("endDate")).sendKeys("2019-06-20");
        driver.findElement(By.id("amountHours")).click();
        assertThat(driver.switchTo().alert().getText(), is("De startdatum moet kleiner zijn dan de einddatum van uw opdracht!"));
    }
    // id= 9
    @Test
    public void allAssignmentsNoChanges() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Opdracht Toevoegen")).click();
        driver.findElement(By.id("title")).click();
        driver.findElement(By.id("title")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("type")).click();
        {
            WebElement dropdown = driver.findElement(By.id("type"));
            dropdown.findElement(By.xpath("//option[. = 'Mobility']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(3)")).click();
        driver.findElement(By.id("task")).click();
        driver.findElement(By.id("task")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("startDate")).click();
        driver.findElement(By.id("startDate")).sendKeys("2019-06-28");
        driver.findElement(By.id("endDate")).click();
        driver.findElement(By.id("endDate")).sendKeys("2019-06-30");
        driver.findElement(By.id("amountHours")).click();
        driver.findElement(By.id("amountHours")).sendKeys("12");
        driver.findElement(By.id("maxStudents")).click();
        driver.findElement(By.id("maxStudents")).sendKeys("5");
        driver.findElement(By.cssSelector(".button")).click();
        driver.findElement(By.cssSelector(".button:nth-child(3)")).click();
        driver.findElement(By.linkText("📃")).click();
        driver.findElement(By.cssSelector(".button:nth-child(1)")).click();
        driver.findElement(By.id("save")).click();
    }
    //id=39
    @Test
    public void assignmentEnrollStudentNotValidated() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 701));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolasstudent@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Lopende Opdrachten")).click();
        driver.findElement(By.cssSelector(".tablebackground:nth-child(2) .button")).click();
    }

    //id= 49
    @Test
    public void archiveAssignmentNotPossibleRole() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 701));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolasstudent@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("assignments")).click();
        driver.findElement(By.linkText("Lopende Opdrachten")).click();
        driver.findElement(By.linkText("📃")).click();
    }
}