package com.architec.crediti;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class SeleniumTagTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\toegepaste informatica\\J2\\M4\\Project\\geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    //id= 18
    @Test
    public void createTagHalfFillIn() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 707));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("tags")).click();
        driver.findElement(By.linkText("Toevoegen")).click();
        driver.findElement(By.id("tagName")).click();
        driver.findElement(By.id("tagName")).sendKeys("SELENIUMtest");
        driver.findElement(By.cssSelector(".btn")).click();
    }

    //id= 19
    @Test
    public void createTagEmpty() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 707));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("tags")).click();
        driver.findElement(By.linkText("Toevoegen")).click();
        driver.findElement(By.cssSelector(".btn")).click();
    }

    //id= 20
    @Test
    public void createTagTooLong() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 707));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("tags")).click();
        driver.findElement(By.linkText("Toevoegen")).click();
        driver.findElement(By.id("tagName")).sendKeys("heelLangeSeleniumTESTNaamDieGroterIsDanVijftigKara");
        driver.findElement(By.id("tagDescription")).click();
        driver.findElement(By.id("tagDescription")).sendKeys("SELENIUMtest");
        driver.findElement(By.cssSelector(".btn")).click();
    }

    //id= 24
    @Test
    public void editTagEmptyField() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("extras")).click();
        driver.findElement(By.linkText("Lijst van Tags")).click();
        driver.findElement(By.linkText("Bewerk")).click();
        driver.findElement(By.linkText("Bewerk")).click();
        driver.findElement(By.id("tagName")).click();
        driver.findElement(By.id("tagName")).sendKeys("");
        driver.findElement(By.id("save")).click();
    }

    //id= 25
    @Test
    public void editTagLongInput() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolas.rossie@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("extras")).click();
        driver.findElement(By.linkText("Lijst van Tags")).click();
        driver.findElement(By.linkText("Bewerk")).click();
        driver.findElement(By.linkText("Bewerk")).click();
        driver.findElement(By.id("tagName")).click();
        driver.findElement(By.id("tagName")).sendKeys("heelLangeSeleniumTESTNaamDieGroterIsDanVijftigKara");
    }
}
