package com.architec.crediti;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class SeleniumLoginRegistrationTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "C:\\toegepaste informatica\\J2\\M4\\Project\\geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }

    //id= 27
    @Test
    public void createExternalUserFewFields() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Registreren")).click();
        driver.findElement(By.id("firstname")).click();
        driver.findElement(By.id("firstname")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("lastname")).click();
        driver.findElement(By.id("lastname")).sendKeys("SELENIUMtest");
        driver.findElement(By.cssSelector(".btn")).click();
    }

    //id= 28
    @Test
    public void createExternalUserEmpty() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Registreren")).click();
        driver.findElement(By.cssSelector(".btn")).click();
    }

    //id= 29
    @Test
    public void createExternalUserWrongEmail() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(1550, 838));
        driver.findElement(By.linkText("Registreren")).click();
        driver.findElement(By.id("firstname")).click();
        driver.findElement(By.id("firstname")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("lastname")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("company")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("address")).click();
        driver.findElement(By.id("address")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("postal")).click();
        driver.findElement(By.id("postal")).sendKeys("0000");
        driver.findElement(By.id("city")).click();
        driver.findElement(By.id("city")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("phone")).click();
        driver.findElement(By.id("phone")).sendKeys("0000");
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("SELENIUMtest");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
    }
    //id= 31
    @Test
    public void createStudentOtherLogin() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 701));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolasstudent@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
    }

    //id= 32
    //TODO breaks tests new hash password
    /*@Test
    public void updateExternalUserProfileNoEdits() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 701));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).sendKeys("nicolasextern@gmail.com");
        driver.findElement(By.id("password")).sendKeys("testwachtwoord");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.id("profile")).click();
        driver.findElement(By.linkText("Mijn profiel")).click();
        driver.findElement(By.name("edit")).click();
        driver.findElement(By.name("save")).click();
    }*/

    //id= 40
    @Test
    public void passwordRecoveryLoad() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 701));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.cssSelector(".mt-5")).click();
        driver.findElement(By.cssSelector("a:nth-child(6) > b")).click();
    }

    //id= 41
    @Test
    public void passwordRecoveryRedirect() {
        driver.get("http://vps092.ap.be/");
        driver.manage().window().setSize(new Dimension(900, 701));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.cssSelector(".mt-5")).click();
        driver.findElement(By.cssSelector("a:nth-child(6) > b")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("emailnotindatabase@test.test");
        driver.findElement(By.cssSelector(".btn")).click();
    }
}
